export const GET_FRIENDS_REQUEST = 'GET_FRIENDS_REQUEST'
export const GET_FRIENDS_SUCCESS = 'GET_FRIENDS_SUCCESS'

export const ADD_FRIEND_REQUEST = 'ADD_FRIEND_REQUEST'
export const ADD_FRIEND_SUCCESS = 'ADD_FRIEND_SUCCESS'

export const REMOVE_FRIEND_REQUEST = 'REMOVE_FRIEND_REQUEST'
export const REMOVE_FRIEND_SUCCESS = 'REMOVE_FRIEND_SUCCESS'

export const SEND_FRIEND_REQUEST = 'SEND_FRIEND_REQUEST'
export const SEND_FRIEND_SUCCESS = 'SEND_FRIEND_SUCCESS'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'