export const CHECK_TODO_REQUEST = 'CHECK_TODO_REQUEST'
export const CHECK_TODO_SUCCESS = 'CHECK_TODO_SUCCESS'
export const CHECK_TODO_RESET = 'CHECK_TODO_RESET'
export const CHECK_TODO_FAIL = 'CHECK_TODO_FAIL'

export const BOOKED_DATES_SUCCESS = 'BOOKED_DATES_SUCCESS'
export const BOOKED_DATES_FAIL = 'BOOKED_DATES_FAIL'

export const MY_TODOS_SUCCESS = 'MY_TODOS_SUCCESS'
export const MY_TODOS_FAIL = 'MY_TODOS_FAIL'

export const TODO_DETAILS_SUCCESS = 'TODO_DETAILS_SUCCESS'
export const TODO_DETAILS_FAIL = 'TODO_DETAILS_FAIL'

export const ADMIN_TODOS_REQUEST = 'ADMIN_TODOS_REQUEST'
export const ADMIN_TODOS_SUCCESS = 'ADMIN_TODOS_SUCCESS'
export const ADMIN_TODOS_FAIL = 'ADMIN_TODOS_FAIL'

export const DELETE_TODO_REQUEST = 'DELETE_TODO_REQUEST'
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS'
export const DELETE_TODO_RESET = 'DELETE_TODO_RESET'
export const DELETE_TODO_FAIL = 'DELETE_TODO_FAIL'

export const NEW_TODO_REQUEST = ' NEW_TODO_REQUEST'
export const NEW_TODO_SUCCESS = ' NEW_TODO_SUCCESS'
export const NEW_TODO_FAIL = ' NEW_TODO_FAIL'

export const GET_TODOS_REQUEST = 'GET_TODOS_REQUEST'
export const GET_TODOS_SUCCESS = 'GET_TODOS_SUCCESS'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'